### ISSUE TITLE
Fine-related endpoints do not work well without a frontend

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-backend#67]
The current fine operations are of insufficient quality. They work well in theory, but in practice the endpoints have some flaws which block the handout of fines. Therefore, these issues should be resolved with some haste.

From what I have heard from @CodeNamedRobin and also experienced myself when observing the usage of these endpoints, the current implementation has the following flaws which should be addressed:

1. The endpoints are not stateless. Some endpoints have an optional reference date, but when this is not used, a previous handout event date is picked. If this does not exist, the current date is picked. This makes using the endpoint very confusing without a frontend, as a user now has to think for themselves what the endpoint should and will do. Therefore, the reference date should be more explicit.
2. For handing out fines, there are actually two reference dates: the previous fine handout event and the date of the new handout event. In the current implementation, the latter reference date cannot be set and is always "now". This is an easier implementation, but makes it impossible to hand out fines the morning after the borrel when issues come up.
3. The endpoints only return IDs of users and not any names. This is fine when a frontend also has a complete list of all users, but this is impossible without it. Therefore, the responses should include the `BaseUserResponse` object to make it clear which user belongs to the given ID.
4. The `GET /fines/eligible` endpoint only gives a list of users and their fines, but does not include any balances. This is by design, because balances should be requested from the `GET /balances` endpoint. However, it is not possible to request a subset of users. The current endpoints only allow requesting one user or all users. Therefore, a filter should be added to the `GET /balances` endpoint to also provide a list of IDs the user wants the balances for.
5. The `GET /fines/eligible` and `POST /fines/handout` endpoints do not return the reference dates used. When the system "assumes" certain dates or parameters, these should be included in the responses to verify that the given result is expected and valid. However, given the flaws given above, there should be no more assumptions made by the system.
6. When a user goes out of debt, the `currentFines` attribute should be set to `null`. However, this does not seem to happen in the production environment. It might have something to do with the different database used (MySQL), but this should be investigated and fixed.

**Todo list to solve this issue**
- [x] Make referenceDate(s) explicit in calls to eligible, handout and notify endpoints
- [x] (Temporarily) include `BaseUserResponse` and balance on all reference dates in response of `GET /fines/eligible`.
- [x] Include reference date(s) in `FineHandoutEvent`.
- [x] Fix `User.currentFines` not being set to `null` when user pays off debt.

**Comment by Yoronex** [comment]
If @CodeNamedRobin or @JustSamuel have anything to add to this issue, please do so!

**Comment by CodeNamedRobin** [comment]
I have looked at the code as well, trying to test it manually, but in that process I have also found another issue. At the moment when using the fines/eligible endpoint, when not putting in a reference date, it always goes to "now". This should, as per the documentation, first pick the date of the last handout event. This is also how the fines/handout endpoint works now, which makes handing out fines a bit confusing as of now.
Me and @JustSamuel also think it would be wise to put in the response the referenceDate used, and if it used the userInput, lastHandoutEvent or Now. 
What do you think @Yoronex

**Comment by Yoronex** [comment]
I have added points 5 and 6 to the description.

**Comment by Yoronex** [comment]
Do we also want to give a response when calling the `POST /fine/notify` endpoint? Because it only sends email to the users you give up for the given date, nothing else. It feels a bit unnecessary to give back a date or list of users that got an email.

**Comment by CodeNamedRobin** [comment]
It doesn't feel necessary in my opinion, as all the IDs are provided by the user when calling the endpoint anyway.
